services:
  - type: web
    name: yapx-update
    runtime: node
    nodeVersion: 18.x
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 